#! /bin/sh

## Hotkey Deamon
sxhkd &

## General Settings
bspc monitor -d I

bspc config border_width         2
bspc config window_gap          12
bspc config ignore_ewmh_struts true

bspc config normal_border_color "#444444"
bspc config focused_border_color "#008080"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle      true


## For Copy Paste Operations in Micro
exec xclip &

## Compositor
exec picom &

## Policy Kit
exec /usr/lib/polkit-kde-authentication-agent-1 &

## Alacritty/Twin
alacritty -e $SHELL -c 'TERM=xterm twin --hw=tty' &

## Fix for Java Programs
export _JAVA_AWT_WM_NONREPARENTING=1 &

## Fix the screen size
bspc config -m focused bottom_padding 0;bspc config -m focused top_padding 0 &

## Put Everything To Monocle
exec ~/.config/bspwm/scripts/monocle &
